name: Build

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: "The release version"
        required: true
        default: "0.0.0"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get current build number
        id: build-number
        run: |
          cd .github/builds
          npm install
          npm run --silent get_number >> $GITHUB_OUTPUT

      - name: Build
        run: ./gradlew build -Pcommit=${{ github.sha }} -Pbuild_number=${{ steps.build-number.outputs.number }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build/
          if-no-files-found: error
